image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Frappe Dev
    init: |
      sudo service mysql start
      sudo service redis-server start
      bench setup requirements
    command: |
      cd frappe-bench || true
      bench start
